version: "3.9"

services:
  php:
    environment:
      PHP_XDEBUG: 1
      PHP_XDEBUG_MODE: coverage
      PHP_XDEBUG_CLIENT_PORT: 9003
      # Use this for windows or mac.
      PHP_XDEBUG_CLIENT_HOST: host.docker.internal
      # Use this for linux.
      # PHP_XDEBUG_CLIENT_HOST: "172.19.0.1"
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_XDEBUG_LOG: /tmp/xdebug.log
