name: Build & Test app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Install Xdebug
      run: |
        pecl install xdebug
        echo "zend_extension=$(find /usr/lib/php/ -name xdebug.so)" | sudo tee -a $(php -i | grep "Loaded Configuration File" | sed -e 's|.* => \(.*\)|\1|') > /dev/null
        echo "xdebug.remote_enable=on" | sudo tee -a $(php -i | grep "Loaded Configuration File" | sed -e 's|.* => \(.*\)|\1|') > /dev/null
        echo "xdebug.remote_autostart=off" | sudo tee -a $(php -i | grep "Loaded Configuration File" | sed -e 's|.* => \(.*\)|\1|') > /dev/null
        echo "xdebug.mode=coverage" | sudo tee -a $(php -i | grep "Loaded Configuration File" | sed -e 's|.* => \(.*\)|\1|') > /dev/null

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run php code sniffer
      run: composer run phpcs

    - name: Run php static analysis
      run: composer run phpstan

    - name: Run pest tests
      run: composer run pest:coverage
